const Location = {
  ENABLED: 1,
  DISABLED: 0,
  STATUS_ACTIVE: 'Active',
  STATUS_INACTIVE: 'InActive',
  STATUS_DRAFT: "Draft",
  DISTRIBUTION_CENTER: 'distribution_center',
  OFFICE_Text:"Office",
  DISTRIBUTION_CENTER_TEXT:'Distribution Center',
  STORE_TEXT:"Store",

  ALLOW_CHECKIN_ENABLED: 1,
  ALLOW_CHECKIN_DISABLED: 0,
  ALLOW_REPLENISHMENT_ENABLED: 1,
  ALLOW_REPLENISHMENT_DISABLED: 0,
  ALLOW_PURCHASE_ENABLED: 1,
  ALLOW_PURCHASE_DISABLED: 0,
  SALES_SETTLEMENT_REQUIRED_ENABLED: 1,
  SALES_SETTLEMENT_REQUIRED_DISABLED: 0,
  TYPE_DISTRIBUTION_CENTER: 1,
  TYPE_OFFICE: 2,
  TYPE_STORE: 3,
  ACTIVE: 1,
  DRAFT:3,
  INACTIVE:2,
};

module.exports = Location;
