
const Product = {
    PRODUCT_STATUS_NEW: "New",
    PRODUCT_STATUS_EXPORTED: "Exported",

    PRODUCT_SELL_OUT_OF_STOCK_ALLOW: "Allow",
    PRODUCT_SELL_OUT_OF_STOCK_DENY: "Deny",

    PRODUCT_SELL_OUT_OF_STOCK_POLICY_CONTINUE: "continue",
    PRODUCT_SELL_OUT_OF_STOCK_POLICY_DENY: "Deny",

    PRODUCT_SELL_OUT_OF_STOCK_POLICY_CONTINUE_VALUE: 1,
    PRODUCT_SELL_OUT_OF_STOCK_POLICY_DENY_VALUE: 0,

    PRODUCT_TAXABLE_YES: "Yes",
    PRODUCT_TAXABLE_NO: "No",

    PRODUCT_SHOPIFY_STATUS_PUBLISHED: "Published",
    PRODUCT_SHOPIFY_STATUS_DRAFT: "Draft",

    FEATURE_ENABLED: 1,
    FEATURE_DISABLED: 0,

    STATUS_ACTIVE_TEXT: "Active",
    STATUS_DRAFT_TEXT: "Draft",
    STATUS_INACTIVE_TEXT: "InActive",

    STATUS_ACTIVE: 1,
    STATUS_DRAFT:3,
    STATUS_INACTIVE:2,

    ALLOW_ONLINE_SALE : 1,
    DENY_ONLINE_SALE :0,

    ALLOW_TRANSFER_PRODUCT_OUT_OF_STOCK: 1,

    DENY_TRANSFER_PRODUCT_OUT_OF_STOCK: 0,

    PRODUCT_SELL_OUT_OF_STOCK_POLICY_DENY_VALUE: 0,
    ALLOW_TRACKING_QUANTITY: 1,
    DENY_TRACKING_QUANTITY:0,

}

module.exports = Product;


