module.exports = {
    PRODUCT_IMAGE_PATH: "media/product",

    PRODUCT_IMAGE_STATUS_ACTIVE: "Active",
    PRODUCT_IMAGE_STATUS_INACTIVE: "Inactive",

    PRODUCT_IMAGE_SHOPIFY_STATUS_NEW: "New",
    PRODUCT_IMAGE_SHOPIFY_STATUS_PENDING: "Pending",
    PRODUCT_IMAGE_SHOPIFY_STATUS_EXPORTED: "Exported",
};
