const Status = {
    // Shift status new

   ALLOW_EDIT_ENABLED : 1,
   ALLOW_EDIT_DISABLED: 0,
    
    UPDATE_QUANTITY_ENABLED : 1,
    UPDATE_QUANTITY_DISABLED : 0,
    LOCATION_PRODUCT_LAST_STOCK_ENTRY_DATE_UPDATE_ENABLED : 1,
    LOCATION_PRODUCT_LAST_STOCK_ENTRY_DATE_UPDATE_DISABLED : 0,
    UPDATE_PRODUCT_PRICE_ENABLED : 1,
    UPDATE_PRODUCT_PRICE_DISABLED : 0,
    ACTIVE_TEXT:"Active",
    INACTIVE_TEXT:"InActive",
    ACTIVE:1,
    INACTIVE:2,
    VALIDATE_AMOUNT_ENABLED : 1,
    VALIDATE_AMOUNT_DISABLED : 0,
    ALLOW_TO_VIEW_ENABLED : 1,
    ALLOW_TO_VIEW_DISABLED : 0,
    UPDATE_ACCOUNT_PRODUCT_ENABLED : 1,
    UPDATE_ACCOUNT_PRODUCT_DISABLED : 0,
    ALLOW_REFUND_ENABLED : 1,
    ALLOW_REFUND_DISABLED : 0,

    GROUP_DRAFT_TEXT: "Draft",
    GROUP_NEW_TEXT: "New",
    GROUP_REVIEW_TEXT: "Review",
    GROUP_PENDING_TEXT: "Pending",
    GROUP_APPROVED_TEXT: "Approved",
    GROUP_COMPLETED_TEXT: "Completed",
    GROUP_CANCELLED_TEXT: "Cancelled",
    GROUP_REOPEN_TEXT: "Reopen",
    GROUP_HOLD_TEXT: "Hold",
    GROUP_INPROGRESS_TEXT: "Inprogress",

    GROUP_DRAFT: 1,
    GROUP_NEW: 2,
    GROUP_REVIEW: 3,
    GROUP_PENDING: 4,
    GROUP_APPROVED: 5,
    GROUP_COMPLETED: 6,
    GROUP_CANCELLED: 7,
    GROUP_INPROGRESS: 8,
    GROUP_REOPEN: 9,
    GROUP_HOLD: 10,

    NOTIFY_TO_OWNER_ENABLED : 1,
    NOTIFY_TO_OWNER_DISABLED : 0,

    NOTIFY_TO_REVIEWER_ENABLED : 1,
    NOTIFY_TO_REVIEWER_DISABLED : 0,

    ALLOW_CANCEL: 1,
    DENY_CANCEL: 0,

    ALLOW_PRODUCT_ADD:1,
    DENY_PRODUCT_ADD:0,

    UPDATE_DISTRIBUTION_QUANTITY_ENABLED: 1,
    UPDATE_DISTRIBUTION_QUANTITY_DISABLED: 0,

    ALLOW_REPLENISHMENT: 1,
    DENY_REPLENISHMENT: 0,

    IS_ACTIVE_PRICE: 1,
    IS_NOT_ACTIVE_PRICE: 0,

    UPDATE_QUANTITY_IN_LOCATION_PRODUCT_ENABLED : 1,
    UPDATE_QUANTITY_IN_LOCATION_PRODUCT_DISABLED : 0,

    NOT_RECEIVED_PRODUCT_ENABLED : 1,
    NOT_RECEIVED_PRODUCT_DISABLED : 0,


    REJECTED_PRODUCT_ENABLED : 1,
    REJECTED_PRODUCT_DISABLED : 0,


    PENDING: 1,
    COMPLETED: 2,
    COMPLETED_TEXT: "Completed",
    PENDING_TEXT: "Pending",
};

module.exports = Status;