const Transfer = {
    STATUS_DRAFT: "Draft",
   TYPE_REFILL_DISTRIBUTION_TEXT: "Refill Distribution",
  TYPE_EXCESS_RETURN_TEXT: "Excess Return",
  TYPE_EXPIRED_RETURN_TEXT: "Expired Return",
  TYPE_ADDITIONAL_DISTRIBUTION_TEXT: 'Additional Distribution',
  TYPE_DAMAGE_RETURN_TEXT: 'Damage Return',
  TYPE_REFILL_DISTRIBUTION: 1,
  TYPE_EXCESS_RETURN: 2,
  TYPE_EXPIRED_RETURN: 3,
  TYPE_ADDITIONAL_DISTRIBUTION: 4,
  TYPE_DAMAGE_RETURN: 5,
  REPLENISHMENT_BY_STOCK: 1,
  REPLENISHMENT_BY_ORDER : 2
}
module.exports = Transfer;