

const User = {
	STATUS_ACTIVE_TEXT: "Active",
	STATUS_INACTIVE_TEXT: "InActive",
	STATUS_ACTIVE:1,
	STATUS_INACTIVE: 2,
	TYPE_SALES_EXECUTIVE: "Sales Executive",
	TYPE_CUSTOMER:"Customer",
	PRIMARY_TYPE:1,
	SECONDARY_TYPE:2,
	LOGGED_IN_USER:-1,
	LOGGED_IN_USER_TEXT: "Logged In User",
	FORCE_LOGOUT_ENABLE : 2,
	FORCE_LOGOUT_DISABLED : 0

}

module.exports = User;